% !Rnw root = ../ProjectReport.Rnw
\begin{table}[h]
\begin{tabular}{|p{4cm}|p{13cm}|}
\hline
\textbf{Member} & \textbf{Contribution} \\ \hline
Bradley Macdonald & Analyze regression models of Figure 4\\ \hline
Tung Huynh & Preprocess Data, create and analyze regression models of Table S2, Table S3\\ \hline
Yifan Zhang & Preprocess Data, and draw plot of Figure 4 \\ \hline
\end{tabular}
\caption{Contribution of group members of the second milestone}
\label{tbl:contribution}
\end{table}
