% !Rnw root = ../ProjectReport.Rnw
\begin{table}[h]
\begin{tabular}{|l|l|}
\hline
\textbf{Member} & \textbf{Contribution} \\ \hline
Bradley Macdonald & Preprocess data and create regression models of Figure 4\\ \hline
Tung Huynh & Preprocess Data, create regression models of Table S4, Table S5\\ \hline
Yifan Zhang & Preprocess Data, and draw plot of Figure 4 \\ \hline
\end{tabular}
\caption{Contribution of group members}
\label{tbl:contribution}
\end{table}
